[env:clock]
platform = espressif32
framework = arduino
board = esp32dev
lib_deps = marcoschwartz/LiquidCrystal_I2C@^1.1.4
build_src_filter = +<controller/>

[env:hello]
platform = espressif32
framework = arduino
board = esp32dev
lib_deps = marcoschwartz/LiquidCrystal_I2C@^1.1.4
build_src_filter = +<hello/>

[env:esp_now]
platform = espressif32
framework = arduino
board = esp32-s3-devkitc-1
build_src_filter = +<esp_now_test/>
monitor_speed = 115200